
before_script:
  - whoami
  - pwd
  - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v8.11.3/bin
check:
  stage: build
  script:
    - node -v
    - npm -v
    - git merge-base HEAD master
    - npx linc
